version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
    - ENV_VARIABLE_NAME=dev